gravitino.exceptions.base.InternalError
=======================================

.. currentmodule:: gravitino.exceptions.base

.. autoexception:: InternalError